### Cek Ongkir JNE
POST https://rajaongkir.komerce.id/api/v1/calculate/domestic-cost
Content-Type: application/x-www-form-urlencoded
Accept: application/json
key: 87HN393p928c709268c5c6c6GomQXz3v

origin=64999&destination=64942&weight=1000&courier=jne